version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - ci
      - github-actions
      - dependencies
    commit-message:
      prefix: ci
      include: scope
