name: Apiclient Publish

on:
  push:
    tags:
      - '*'
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-20.04
    environment: release
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11
      - name: Set JELLYFIN_VERSION
        if: ${{ startsWith(github.ref, 'refs/tags') }}
        run: echo "JELLYFIN_VERSION=$(echo ${GITHUB_REF#refs/tags/} | tr / -)" >> $GITHUB_ENV
      - name: Run publish task
        run: ./gradlew --no-daemon --info publish
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          OSSRH_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          OSSRH_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}
